export const CDGtoSEA = `<AirShoppingRQ xmlns="http://www.iata.org/IATA/2015/00/2018.1/AirShoppingRQ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Party>
		<Sender>
			<TravelAgency>
				<AgencyID>HACK-TST</AgencyID>
				<IATA_Number>1234</IATA_Number>
				<Name>Hackathon</Name>
				<PseudoCityID>BJS</PseudoCityID>
			</TravelAgency>
		</Sender>
	</Party>
	<Request>
		<FlightRequest>
			<OriginDestRequest>
				<OriginDestID/>
				<ConnectionCriteriaRefID/>
				<DestArrivalRequest>
					<IATA_LocationCode>SEA</IATA_LocationCode>
					<Date>2019-04-08</Date>
				</DestArrivalRequest>
				<OriginDepRequest>
					<IATA_LocationCode>CDG</IATA_LocationCode>
					<Date>2019-04-08</Date>
				</OriginDepRequest>
			</OriginDestRequest>
		</FlightRequest>
		<Paxs>
			<Pax>
				<PaxID>PaxRefID1</PaxID>
				<PTC>ADT</PTC>
			</Pax>
			<!--Pax>
            <PaxID>PaxRefID2</PaxID>
            <PTC>INF</PTC>
         </Pax>
         <Pax>
            <PaxID>PaxRefID3</PaxID>
            <PTC>GBE</PTC>
         </Pax>
         <Pax>
            <PaxID>PaxRefID4</PaxID>
            <PTC>CNN</PTC>
         </Pax>
         <Pax>
            <PaxID>PaxRefID5</PaxID>
            <PTC>ADT</PTC>
         </Pax-->
		</Paxs>
		<ResponseParameters>
			<CurParameter>
				<CurCode>USD</CurCode>
			</CurParameter>
		</ResponseParameters>
		<ShoppingCriteria/>
	</Request>
</AirShoppingRQ>`
